GET http://localhost:3000/libros

POST http://localhost:3000/libros
Content-Type: application/json

{
  "titulo": "La Odisea",
  "autor": "Homero",
  "anioPublicacion": 800,
  "genero": {
    "nombre": "Épico",
    "codigo": "EP"
  }
}
